# Use the OpenJDK 17 JDK on Alpine Linux as the base image
FROM openjdk:17-jdk-alpine

# Set JAVA_HOME and update PATH
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH

# Set the working directory in the container
WORKDIR /app

# Copy your project files
COPY mvnw pom.xml ./
COPY .mvn .mvn
COPY src src

# Make sure the Maven wrapper is executable and build the project
RUN chmod +x mvnw && ./mvnw clean package -DskipTests

# Expose the port your application runs on
EXPOSE 8181

# Run the application
CMD ["java", "-jar", "target/*.jar"]
