services:
  - type: web
    name: my-java-app
    env: docker
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    autoDeploy: true
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
