services:
  - type: web
    name: narayan-travels
    env: docker
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/smartcontactmanager-0.0.1.jar"
    autoDeploy: true
    envVars:
      - key: JAVA_HOME
        value: "/opt/openjdk-17"
