services:
  - type: web
    name: narayan-travels
    env: docker
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    autoDeploy: true
    envVars:
      - key: JAVA_HOME
        value: "C:/Program Files/Java/jdk-17"
